- name: Install httpd
  yum:
    name: httpd
    state: present

- name: Ensure httpd is enabled
  service:
    name: httpd
    enabled: true
    state: started

- name: Install mod_wsgi to serve apache
  yum:
    name: mod_wsgi
    state: present

- name: Configure Django apache.conf
  template:
    src: template.j2
    dest: /etc/httpd/conf.d/django.conf
    owner: root
    group: root
    mode: 0644

- name: Update apache group permissions
  file:
    path: /vagrant/users_project
    state: directory
    owner: vagrant
    group: apache
    mode: 0775
