---
- hosts: all
  become: yes
  tasks:
    - name: Include roles
      include_role:
        name: "{{ item }}"
      with_items:
        - httpd
        - yum

    - name: Create python venv
      pip:
        requirements: /vagrant/requirments.txt
        virtualenv: /vagrant
        virtualenv_command: /usr/bin/python3.6 -m venv
